name: testRigor

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: |
          # Trigger the TestRigor retest
          curl -X POST \
            -H 'Content-type: application/json' \
            -H 'auth-token: ec8d3bb8-f75a-46f5-8902-f554d40e722d' \
            --data '{"forceCancelPreviousTesting":true,"storedValues":{"storedValueName1":"Value"}}' \
            https://api.testrigor.com/api/v1/apps/GhXKpRB7muG3ur2ku/retest

          sleep 10

          while true; do
            echo " "
            echo "==================================="
            echo " Checking TestRigor retest"
            echo "==================================="

            response=$(curl -i -o - -s -X GET \
              https://api.testrigor.com/api/v1/apps/GhXKpRB7muG3ur2ku/status \
              -H 'auth-token: ec8d3bb8-f75a-46f5-8902-f554d40e722d' \
              -H 'Accept: application/json')

            code=$(echo "$response" | grep HTTP | awk '{print $2}')
            body=$(echo "$response" | sed -n '/{/,/}/p')

            echo "Status code: $code"
            echo "Response: $body"

            case $code in
              4*|5*)
                # 400 or 500 errors
                echo "Error calling API"
                exit 1
                ;;
              200)
                # 200: successfully finished
                echo "Test finished successfully"
                exit 0
                ;;
              227|228)
                # 227: New - 228: In progress
                echo "Test is not finished yet"
                ;;
              230)
                # 230: Failed
                echo "Test finished but failed"
                exit 1
                ;;
              *)
                echo "Unknown status"
                exit 1
                ;;
            esac

            sleep 10
          done
